version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: smart_mysql
    environment:
        MYSQL_ROOT_PASSWORD: hea1thy
        MYSQL_DATABASE: smart_apartment
    ports:
        - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

  redis:
    image: redis:7.0
    container_name: smart_redis
    ports:
      - "6379:6379"
    restart: always